<?php

namespace Database\Seeders;

use App\Models\Club;
use App\Models\Confederation;
use App\Models\Federation;
use App\Models\Player;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ColombiaSeeder extends Seeder
{
    public function run(): void
    {
        $conmebol = Confederation::where('name', 'CONMEBOL')->firstOrFail();

        $colombia = Federation::updateOrCreate(
            ['country_code' => 'COL'],
            [
                'confederation_id'    => $conmebol->id,
                'name'                => 'Federación Colombiana de Fútbol',
                'short_name'          => 'FCF',
                'country'             => 'Colombia',
                'country_code'        => 'COL',
                'continent'           => 'South America',
                'city'                => 'Bogotá',
                'president'           => 'Ramón Jesurún',
                'head_coach'          => 'Néstor Lorenzo',
                'founded_year'        => 1924,
                'fifa_ranking'        => 13,
                'world_cup_appearances' => 7,
                'world_cup_titles'    => 0,
                'best_result'         => 'Cuartos de final (Brasil 2014)',
                'national_stadium'    => 'Estadio El Campín',
                'stadium_capacity'    => 36343,
                'primary_color'       => '#FCD116',
                'secondary_color'     => '#003087',
                'website'             => 'https://fcf.com.co',
                'logo_url'            => 'federations/colombia.png',
                'latitude'            => 4.7110,
                'longitude'           => -74.0721,
                'qualified_wc_2026'   => true,
            ]
        );

        $this->seedClubs();
        $this->seedPlayers($colombia->id);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // CLUBES
    // ─────────────────────────────────────────────────────────────────────────
    private function seedClubs(): void
    {
        $clubs = [
            // ── Colombia ──────────────────────────────────────────────────────
            [
                'name'              => 'Atlético Nacional',
                'short_name'        => 'Nacional',
                'country'           => 'Colombia',
                'country_code'      => 'COL',
                'city'              => 'Medellín',
                'stadium_name'      => 'Estadio Atanasio Girardot',
                'stadium_capacity'  => 40943,
                'founded_year'      => 1947,
                'league_name'       => 'Liga BetPlay Dimayor',
                'latitude'          => 6.2530,
                'longitude'         => -75.5893,
            ],
            [
                'name'              => 'Independiente Santa Fe',
                'short_name'        => 'Santa Fe',
                'country'           => 'Colombia',
                'country_code'      => 'COL',
                'city'              => 'Bogotá',
                'stadium_name'      => 'Estadio El Campín',
                'stadium_capacity'  => 36343,
                'founded_year'      => 1941,
                'league_name'       => 'Liga BetPlay Dimayor',
                'latitude'          => 4.6470,
                'longitude'         => -74.0856,
            ],
            [
                'name'              => 'Deportes Tolima',
                'short_name'        => 'Tolima',
                'country'           => 'Colombia',
                'country_code'      => 'COL',
                'city'              => 'Ibagué',
                'stadium_name'      => 'Estadio Manuel Murillo Toro',
                'stadium_capacity'  => 26000,
                'founded_year'      => 1954,
                'league_name'       => 'Liga BetPlay Dimayor',
                'latitude'          => 4.4389,
                'longitude'         => -75.2007,
            ],

            // ── Argentina ─────────────────────────────────────────────────────
            [
                'name'              => 'Vélez Sarsfield',
                'short_name'        => 'Vélez',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Buenos Aires',
                'stadium_name'      => 'Estadio José Amalfitani',
                'stadium_capacity'  => 49540,
                'founded_year'      => 1910,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -34.6485,
                'longitude'         => -58.5286,
            ],
            [
                'name'              => 'Club Atlético Independiente',
                'short_name'        => 'Independiente',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Avellaneda',
                'stadium_name'      => 'Estadio Libertadores de América',
                'stadium_capacity'  => 42701,
                'founded_year'      => 1905,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -34.6651,
                'longitude'         => -58.3587,
            ],
            [
                'name'              => 'San Lorenzo',
                'short_name'        => 'San Lorenzo',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Buenos Aires',
                'stadium_name'      => 'Estadio Pedro Bidegain',
                'stadium_capacity'  => 47964,
                'founded_year'      => 1908,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -34.6336,
                'longitude'         => -58.4175,
            ],
            [
                'name'              => 'River Plate',
                'short_name'        => 'River',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Buenos Aires',
                'stadium_name'      => 'Estadio Monumental',
                'stadium_capacity'  => 84567,
                'founded_year'      => 1901,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -34.5454,
                'longitude'         => -58.4499,
            ],
            [
                'name'              => 'Independiente Rivadavia',
                'short_name'        => 'Rivadavia',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Mendoza',
                'stadium_name'      => 'Estadio Libertador Gral. San Martín',
                'stadium_capacity'  => 38000,
                'founded_year'      => 1905,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -32.8895,
                'longitude'         => -68.8458,
            ],
            [
                'name'              => 'Estudiantes de La Plata',
                'short_name'        => 'Estudiantes',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'La Plata',
                'stadium_name'      => 'Estadio Ciudad de La Plata',
                'stadium_capacity'  => 53000,
                'founded_year'      => 1905,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -34.9014,
                'longitude'         => -57.9861,
            ],
            [
                'name'              => 'Rosario Central',
                'short_name'        => 'Central',
                'country'           => 'Argentina',
                'country_code'      => 'ARG',
                'city'              => 'Rosario',
                'stadium_name'      => 'Estadio Dr. Lisandro de la Torre',
                'stadium_capacity'  => 41654,
                'founded_year'      => 1889,
                'league_name'       => 'Primera División Argentina',
                'latitude'          => -32.9558,
                'longitude'         => -60.6567,
            ],

            // ── México ────────────────────────────────────────────────────────
            [
                'name'              => 'Atlas',
                'short_name'        => 'Atlas',
                'country'           => 'México',
                'country_code'      => 'MEX',
                'city'              => 'Guadalajara',
                'stadium_name'      => 'Estadio Jalisco',
                'stadium_capacity'  => 55161,
                'founded_year'      => 1916,
                'league_name'       => 'Liga MX',
                'latitude'          => 20.6767,
                'longitude'         => -103.3472,
            ],
            [
                'name'              => 'Cruz Azul',
                'short_name'        => 'Cruz Azul',
                'country'           => 'México',
                'country_code'      => 'MEX',
                'city'              => 'Ciudad de México',
                'stadium_name'      => 'Estadio Ciudad de los Deportes',
                'stadium_capacity'  => 33000,
                'founded_year'      => 1927,
                'league_name'       => 'Liga MX',
                'latitude'          => 19.3751,
                'longitude'         => -99.1881,
            ],
            [
                'name'              => 'Pumas UNAM',
                'short_name'        => 'Pumas',
                'country'           => 'México',
                'country_code'      => 'MEX',
                'city'              => 'Ciudad de México',
                'stadium_name'      => 'Estadio Olímpico Universitario',
                'stadium_capacity'  => 72449,
                'founded_year'      => 1954,
                'league_name'       => 'Liga MX',
                'latitude'          => 19.3033,
                'longitude'         => -99.1836,
            ],
            [
                'name'              => 'Club América',
                'short_name'        => 'América',
                'country'           => 'México',
                'country_code'      => 'MEX',
                'city'              => 'Ciudad de México',
                'stadium_name'      => 'Estadio Azteca',
                'stadium_capacity'  => 87523,
                'founded_year'      => 1916,
                'league_name'       => 'Liga MX',
                'latitude'          => 19.3028,
                'longitude'         => -99.1500,
            ],

            // ── Ecuador ───────────────────────────────────────────────────────
            [
                'name'              => 'Independiente del Valle',
                'short_name'        => 'IDV',
                'country'           => 'Ecuador',
                'country_code'      => 'ECU',
                'city'              => 'Sangolquí',
                'stadium_name'      => 'Estadio Rumiñahui',
                'stadium_capacity'  => 10000,
                'founded_year'      => 1958,
                'league_name'       => 'Liga Pro Ecuador',
                'latitude'          => -0.3152,
                'longitude'         => -78.4482,
            ],

            // ── Inglaterra ────────────────────────────────────────────────────
            [
                'name'              => 'Crystal Palace',
                'short_name'        => 'Palace',
                'country'           => 'England',
                'country_code'      => 'ENG',
                'city'              => 'London',
                'stadium_name'      => 'Selhurst Park',
                'stadium_capacity'  => 25486,
                'founded_year'      => 1905,
                'league_name'       => 'Premier League',
                'latitude'          => 51.3983,
                'longitude'         => -0.0855,
            ],
            [
                'name'              => 'Wolverhampton Wanderers',
                'short_name'        => 'Wolves',
                'country'           => 'England',
                'country_code'      => 'ENG',
                'city'              => 'Wolverhampton',
                'stadium_name'      => 'Molineux Stadium',
                'stadium_capacity'  => 32050,
                'founded_year'      => 1877,
                'league_name'       => 'Premier League',
                'latitude'          => 52.5900,
                'longitude'         => -2.1300,
            ],
            [
                'name'              => 'Birmingham City',
                'short_name'        => 'Birmingham',
                'country'           => 'England',
                'country_code'      => 'ENG',
                'city'              => 'Birmingham',
                'stadium_name'      => "St. Andrew's",
                'stadium_capacity'  => 29409,
                'founded_year'      => 1875,
                'league_name'       => 'Championship',
                'latitude'          => 52.4763,
                'longitude'         => -1.7772,
            ],

            // ── Italia ────────────────────────────────────────────────────────
            [
                'name'              => 'Bologna',
                'short_name'        => 'Bologna',
                'country'           => 'Italy',
                'country_code'      => 'ITA',
                'city'              => 'Bologna',
                'stadium_name'      => "Stadio Renato Dall'Ara",
                'stadium_capacity'  => 38279,
                'founded_year'      => 1909,
                'league_name'       => 'Serie A',
                'latitude'          => 44.4921,
                'longitude'         => 11.3092,
            ],
            [
                'name'              => 'Cagliari',
                'short_name'        => 'Cagliari',
                'country'           => 'Italy',
                'country_code'      => 'ITA',
                'city'              => 'Cagliari',
                'stadium_name'      => 'Unipol Domus',
                'stadium_capacity'  => 16416,
                'founded_year'      => 1920,
                'league_name'       => 'Serie A',
                'latitude'          => 39.2034,
                'longitude'         => 9.1375,
            ],
            [
                'name'              => 'Juventus',
                'short_name'        => 'Juve',
                'country'           => 'Italy',
                'country_code'      => 'ITA',
                'city'              => 'Turin',
                'stadium_name'      => 'Allianz Stadium',
                'stadium_capacity'  => 41507,
                'founded_year'      => 1897,
                'league_name'       => 'Serie A',
                'latitude'          => 45.1096,
                'longitude'         => 7.6413,
            ],
            [
                'name'              => 'Pisa Calcio',
                'short_name'        => 'Pisa',
                'country'           => 'Italy',
                'country_code'      => 'ITA',
                'city'              => 'Pisa',
                'stadium_name'      => 'Arena Garibaldi',
                'stadium_capacity'  => 14075,
                'founded_year'      => 1909,
                'league_name'       => 'Serie B',
                'latitude'          => 43.7228,
                'longitude'         => 10.4173,
            ],

            // ── Turquía ───────────────────────────────────────────────────────
            [
                'name'              => 'Galatasaray',
                'short_name'        => 'Galatasaray',
                'country'           => 'Turkey',
                'country_code'      => 'TUR',
                'city'              => 'Istanbul',
                'stadium_name'      => 'RAMS Park',
                'stadium_capacity'  => 52694,
                'founded_year'      => 1905,
                'league_name'       => 'Süper Lig',
                'latitude'          => 41.0765,
                'longitude'         => 28.7985,
            ],

            // ── España ────────────────────────────────────────────────────────
            [
                'name'              => 'RCD Mallorca',
                'short_name'        => 'Mallorca',
                'country'           => 'Spain',
                'country_code'      => 'ESP',
                'city'              => 'Palma de Mallorca',
                'stadium_name'      => 'Estadio de Son Moix',
                'stadium_capacity'  => 23142,
                'founded_year'      => 1916,
                'league_name'       => 'La Liga',
                'latitude'          => 39.5903,
                'longitude'         => 2.6635,
            ],
            [
                'name'              => 'Real Betis',
                'short_name'        => 'Betis',
                'country'           => 'Spain',
                'country_code'      => 'ESP',
                'city'              => 'Sevilla',
                'stadium_name'      => 'Estadio Benito Villamarín',
                'stadium_capacity'  => 60720,
                'founded_year'      => 1907,
                'league_name'       => 'La Liga',
                'latitude'          => 37.3562,
                'longitude'         => -5.9811,
            ],
            [
                'name'              => 'Racing de Santander',
                'short_name'        => 'Racing',
                'country'           => 'Spain',
                'country_code'      => 'ESP',
                'city'              => 'Santander',
                'stadium_name'      => 'Campos de Sport de El Sardinero',
                'stadium_capacity'  => 22429,
                'founded_year'      => 1913,
                'league_name'       => 'Primera Federación',
                'latitude'          => 43.4627,
                'longitude'         => -3.8232,
            ],

            // ── Brasil ────────────────────────────────────────────────────────
            [
                'name'              => 'Vasco da Gama',
                'short_name'        => 'Vasco',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Rio de Janeiro',
                'stadium_name'      => 'Estádio São Januário',
                'stadium_capacity'  => 22053,
                'founded_year'      => 1898,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -22.8886,
                'longitude'         => -43.1906,
            ],
            [
                'name'              => 'Flamengo',
                'short_name'        => 'Flamengo',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Rio de Janeiro',
                'stadium_name'      => 'Estádio do Maracanã',
                'stadium_capacity'  => 78838,
                'founded_year'      => 1895,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -22.9120,
                'longitude'         => -43.2301,
            ],
            [
                'name'              => 'Coritiba',
                'short_name'        => 'Coritiba',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Curitiba',
                'stadium_name'      => 'Estádio Couto Pereira',
                'stadium_capacity'  => 40502,
                'founded_year'      => 1909,
                'league_name'       => 'Brasileirão Série B',
                'latitude'          => -25.4278,
                'longitude'         => -49.2753,
            ],
            [
                'name'              => 'Athletico Paranaense',
                'short_name'        => 'Athletico',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Curitiba',
                'stadium_name'      => 'Arena da Baixada',
                'stadium_capacity'  => 42372,
                'founded_year'      => 1924,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -25.4478,
                'longitude'         => -49.2764,
            ],
            [
                'name'              => 'Botafogo',
                'short_name'        => 'Botafogo',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Rio de Janeiro',
                'stadium_name'      => 'Estádio Nilton Santos',
                'stadium_capacity'  => 46069,
                'founded_year'      => 1894,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -22.8588,
                'longitude'         => -43.2286,
            ],
            [
                'name'              => 'Palmeiras',
                'short_name'        => 'Palmeiras',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'São Paulo',
                'stadium_name'      => 'Arena Palmeiras (Allianz Parque)',
                'stadium_capacity'  => 43713,
                'founded_year'      => 1914,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -23.5267,
                'longitude'         => -46.6817,
            ],
            [
                'name'              => 'Cruzeiro',
                'short_name'        => 'Cruzeiro',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Belo Horizonte',
                'stadium_name'      => 'Estádio Mineirão',
                'stadium_capacity'  => 61927,
                'founded_year'      => 1921,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -19.8659,
                'longitude'         => -43.9706,
            ],
            [
                'name'              => 'Internacional',
                'short_name'        => 'Inter',
                'country'           => 'Brazil',
                'country_code'      => 'BRA',
                'city'              => 'Porto Alegre',
                'stadium_name'      => 'Estádio Beira-Rio',
                'stadium_capacity'  => 50128,
                'founded_year'      => 1909,
                'league_name'       => 'Brasileirão Série A',
                'latitude'          => -30.0653,
                'longitude'         => -51.2334,
            ],

            // ── Francia ───────────────────────────────────────────────────────
            [
                'name'              => 'FC Nantes',
                'short_name'        => 'Nantes',
                'country'           => 'France',
                'country_code'      => 'FRA',
                'city'              => 'Nantes',
                'stadium_name'      => 'Stade de la Beaujoire',
                'stadium_capacity'  => 37473,
                'founded_year'      => 1943,
                'league_name'       => 'Ligue 1',
                'latitude'          => 47.2553,
                'longitude'         => -1.5253,
            ],

            // ── Canadá / MLS ──────────────────────────────────────────────────
            [
                'name'              => 'Vancouver Whitecaps',
                'short_name'        => 'Vancouver',
                'country'           => 'Canada',
                'country_code'      => 'CAN',
                'city'              => 'Vancouver',
                'stadium_name'      => 'BC Place',
                'stadium_capacity'  => 22120,
                'founded_year'      => 2009,
                'league_name'       => 'Major League Soccer',
                'latitude'          => 49.2767,
                'longitude'         => -123.1118,
            ],

            // ── Estados Unidos / MLS ──────────────────────────────────────────
            [
                'name'              => 'Minnesota United',
                'short_name'        => 'Minnesota',
                'country'           => 'United States',
                'country_code'      => 'USA',
                'city'              => 'Minneapolis',
                'stadium_name'      => 'Allianz Field',
                'stadium_capacity'  => 19400,
                'founded_year'      => 2010,
                'league_name'       => 'Major League Soccer',
                'latitude'          => 44.9533,
                'longitude'         => -93.1647,
            ],

            // ── Rusia ─────────────────────────────────────────────────────────
            [
                'name'              => 'Zenit',
                'short_name'        => 'Zenit',
                'country'           => 'Russia',
                'country_code'      => 'RUS',
                'city'              => 'Saint Petersburg',
                'stadium_name'      => 'Gazprom Arena',
                'stadium_capacity'  => 68134,
                'founded_year'      => 1925,
                'league_name'       => 'Russian Premier League',
                'latitude'          => 59.9730,
                'longitude'         => 30.2205,
            ],
            [
                'name'              => 'Krasnodar',
                'short_name'        => 'Krasnodar',
                'country'           => 'Russia',
                'country_code'      => 'RUS',
                'city'              => 'Krasnodar',
                'stadium_name'      => 'Krasnodar Stadium',
                'stadium_capacity'  => 33979,
                'founded_year'      => 2008,
                'league_name'       => 'Russian Premier League',
                'latitude'          => 45.0344,
                'longitude'         => 39.0553,
            ],

            // ── Portugal ──────────────────────────────────────────────────────
            [
                'name'              => 'Benfica',
                'short_name'        => 'Benfica',
                'country'           => 'Portugal',
                'country_code'      => 'POR',
                'city'              => 'Lisbon',
                'stadium_name'      => 'Estádio da Luz',
                'stadium_capacity'  => 64642,
                'founded_year'      => 1904,
                'league_name'       => 'Primeira Liga',
                'latitude'          => 38.7528,
                'longitude'         => -9.1845,
            ],
            [
                'name'              => 'Sporting CP',
                'short_name'        => 'Sporting',
                'country'           => 'Portugal',
                'country_code'      => 'POR',
                'city'              => 'Lisbon',
                'stadium_name'      => 'Estádio José Alvalade',
                'stadium_capacity'  => 50095,
                'founded_year'      => 1906,
                'league_name'       => 'Primeira Liga',
                'latitude'          => 38.7613,
                'longitude'         => -9.1609,
            ],

            // ── Alemania ──────────────────────────────────────────────────────
            [
                'name'              => 'Bayern Munich',
                'short_name'        => 'Bayern',
                'country'           => 'Germany',
                'country_code'      => 'GER',
                'city'              => 'Munich',
                'stadium_name'      => 'Allianz Arena',
                'stadium_capacity'  => 75000,
                'founded_year'      => 1900,
                'league_name'       => 'Bundesliga',
                'latitude'          => 48.2188,
                'longitude'         => 11.6247,
            ],
        ];

        foreach ($clubs as $data) {
            Club::updateOrCreate(['name' => $data['name']], $data);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // JUGADORES — prelista 55 convocados Mundial 2026
    // ─────────────────────────────────────────────────────────────────────────
    private function seedPlayers(int $federationId): void
    {
        $players = [
            // ── ARQUEROS ─────────────────────────────────────────────────────
            [
                'first_name'          => 'David',
                'last_name'           => 'Ospina',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '1988-08-31',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 183,
                'weight_kg'           => 80,
                'international_caps'  => 115,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Atlético Nacional',
            ],
            [
                'first_name'          => 'Álvaro',
                'last_name'           => 'Montero',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '1996-09-25',
                'place_of_birth'      => 'Cartagena de Indias, Bolívar',
                'height_cm'           => 183,
                'weight_kg'           => 79,
                'international_caps'  => 12,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Vélez Sarsfield',
            ],
            [
                'first_name'          => 'Camilo',
                'last_name'           => 'Vargas',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '1992-03-27',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 190,
                'weight_kg'           => 82,
                'international_caps'  => 18,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Atlas',
            ],
            [
                'first_name'          => 'Andrés',
                'last_name'           => 'Mosquera Marmolejo',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '1989-10-15',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 186,
                'weight_kg'           => 82,
                'international_caps'  => 5,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Independiente Santa Fe',
            ],
            [
                'first_name'          => 'Aldair',
                'last_name'           => 'Quintana',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '1995-07-04',
                'place_of_birth'      => 'Montería, Córdoba',
                'height_cm'           => 193,
                'weight_kg'           => 88,
                'international_caps'  => 8,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Independiente del Valle',
            ],
            [
                'first_name'          => 'Kevin',
                'last_name'           => 'Mier',
                'position'            => 'goalkeeper',
                'date_of_birth'       => '2000-04-14',
                'place_of_birth'      => 'Barranquilla, Atlántico',
                'height_cm'           => 188,
                'weight_kg'           => 82,
                'international_caps'  => 3,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Cruz Azul',
            ],

            // ── DEFENSORES ───────────────────────────────────────────────────
            [
                'first_name'          => 'Daniel',
                'last_name'           => 'Muñoz',
                'position'            => 'defender',
                'date_of_birth'       => '1996-05-04',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 178,
                'weight_kg'           => 73,
                'international_caps'  => 38,
                'international_goals' => 4,
                'strong_foot'         => 'right',
                'club'                => 'Crystal Palace',
            ],
            [
                'first_name'          => 'Jhon',
                'last_name'           => 'Lucumí',
                'position'            => 'defender',
                'date_of_birth'       => '1999-06-23',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 188,
                'weight_kg'           => 82,
                'international_caps'  => 28,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Bologna',
            ],
            [
                'first_name'          => 'Álvaro',
                'last_name'           => 'Angulo',
                'position'            => 'defender',
                'date_of_birth'       => '1999-06-13',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 172,
                'weight_kg'           => 70,
                'international_caps'  => 6,
                'international_goals' => 0,
                'strong_foot'         => 'left',
                'club'                => 'Pumas UNAM',
            ],
            [
                'first_name'          => 'Santiago',
                'last_name'           => 'Arias',
                'position'            => 'defender',
                'date_of_birth'       => '1992-01-13',
                'place_of_birth'      => 'Santa Rosa de Osos, Antioquia',
                'height_cm'           => 173,
                'weight_kg'           => 66,
                'international_caps'  => 63,
                'international_goals' => 4,
                'strong_foot'         => 'right',
                'club'                => 'Club Atlético Independiente',
            ],
            [
                'first_name'          => 'Davinson',
                'last_name'           => 'Sánchez',
                'position'            => 'defender',
                'date_of_birth'       => '1996-06-12',
                'place_of_birth'      => 'Caloto, Cauca',
                'height_cm'           => 187,
                'weight_kg'           => 81,
                'international_caps'  => 82,
                'international_goals' => 7,
                'strong_foot'         => 'right',
                'club'                => 'Galatasaray',
            ],
            [
                'first_name'          => 'Johan',
                'last_name'           => 'Mojica',
                'position'            => 'defender',
                'date_of_birth'       => '1992-08-21',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 180,
                'weight_kg'           => 77,
                'international_caps'  => 45,
                'international_goals' => 2,
                'strong_foot'         => 'left',
                'club'                => 'RCD Mallorca',
            ],
            [
                'first_name'          => 'Yerry',
                'last_name'           => 'Mina',
                'position'            => 'defender',
                'date_of_birth'       => '1994-09-23',
                'place_of_birth'      => 'Guachené, Cauca',
                'height_cm'           => 194,
                'weight_kg'           => 90,
                'international_caps'  => 58,
                'international_goals' => 9,
                'strong_foot'         => 'right',
                'club'                => 'Cagliari',
            ],
            [
                'first_name'          => 'Cristian',
                'last_name'           => 'Borja',
                'position'            => 'defender',
                'date_of_birth'       => '1993-04-25',
                'place_of_birth'      => 'Tumaco, Nariño',
                'height_cm'           => 177,
                'weight_kg'           => 70,
                'international_caps'  => 32,
                'international_goals' => 1,
                'strong_foot'         => 'left',
                'club'                => 'Club América',
            ],
            [
                'first_name'          => 'Juan',
                'last_name'           => 'Cabal',
                'position'            => 'defender',
                'date_of_birth'       => '2001-01-08',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 183,
                'weight_kg'           => 75,
                'international_caps'  => 22,
                'international_goals' => 2,
                'strong_foot'         => 'left',
                'club'                => 'Juventus',
            ],
            [
                'first_name'          => 'Carlos',
                'last_name'           => 'Cuesta',
                'position'            => 'defender',
                'date_of_birth'       => '1999-04-17',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 183,
                'weight_kg'           => 78,
                'international_caps'  => 18,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Vasco da Gama',
            ],
            [
                'first_name'          => 'Willer',
                'last_name'           => 'Ditta',
                'position'            => 'defender',
                'date_of_birth'       => '1995-11-14',
                'place_of_birth'      => 'Barranquilla, Atlántico',
                'height_cm'           => 183,
                'weight_kg'           => 78,
                'international_caps'  => 8,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Cruz Azul',
            ],
            [
                'first_name'          => 'Junior',
                'last_name'           => 'Hernández',
                'position'            => 'defender',
                'date_of_birth'       => '2001-03-30',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 178,
                'weight_kg'           => 72,
                'international_caps'  => 4,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Deportes Tolima',
            ],
            [
                'first_name'          => 'Deiver',
                'last_name'           => 'Machado',
                'position'            => 'defender',
                'date_of_birth'       => '1995-05-13',
                'place_of_birth'      => 'Quibdó, Chocó',
                'height_cm'           => 172,
                'weight_kg'           => 68,
                'international_caps'  => 22,
                'international_goals' => 1,
                'strong_foot'         => 'left',
                'club'                => 'FC Nantes',
            ],
            [
                'first_name'          => 'Yerson',
                'last_name'           => 'Mosquera',
                'position'            => 'defender',
                'date_of_birth'       => '2001-04-09',
                'place_of_birth'      => 'Quibdó, Chocó',
                'height_cm'           => 183,
                'weight_kg'           => 75,
                'international_caps'  => 14,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Wolverhampton Wanderers',
            ],
            [
                'first_name'          => 'Édier',
                'last_name'           => 'Ocampo',
                'position'            => 'defender',
                'date_of_birth'       => '1994-08-10',
                'place_of_birth'      => 'Guapi, Cauca',
                'height_cm'           => 177,
                'weight_kg'           => 72,
                'international_caps'  => 6,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Vancouver Whitecaps',
            ],
            [
                'first_name'          => 'Jhojan',
                'last_name'           => 'Romaña',
                'position'            => 'defender',
                'date_of_birth'       => '1999-06-25',
                'place_of_birth'      => 'Montería, Córdoba',
                'height_cm'           => 183,
                'weight_kg'           => 78,
                'international_caps'  => 3,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'San Lorenzo',
            ],
            [
                'first_name'          => 'Andrés',
                'last_name'           => 'Román',
                'position'            => 'defender',
                'date_of_birth'       => '1998-10-14',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 180,
                'weight_kg'           => 76,
                'international_caps'  => 8,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Atlético Nacional',
            ],

            // ── MEDIOCAMPISTAS ───────────────────────────────────────────────
            [
                'first_name'          => 'James',
                'last_name'           => 'Rodríguez',
                'position'            => 'midfielder',
                'date_of_birth'       => '1991-07-12',
                'place_of_birth'      => 'Cúcuta, Norte de Santander',
                'height_cm'           => 181,
                'weight_kg'           => 75,
                'international_caps'  => 107,
                'international_goals' => 29,
                'strong_foot'         => 'right',
                'club'                => 'Minnesota United',
            ],
            [
                'first_name'          => 'Jorge',
                'last_name'           => 'Carrascal',
                'position'            => 'midfielder',
                'date_of_birth'       => '1998-02-22',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 170,
                'weight_kg'           => 68,
                'international_caps'  => 20,
                'international_goals' => 3,
                'strong_foot'         => 'right',
                'club'                => 'Flamengo',
            ],
            [
                'first_name'          => 'Sebastián',
                'last_name'           => 'Gómez',
                'position'            => 'midfielder',
                'date_of_birth'       => '1997-06-26',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 176,
                'weight_kg'           => 70,
                'international_caps'  => 15,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Coritiba',
            ],
            [
                'first_name'          => 'Nelson',
                'last_name'           => 'Deossa',
                'position'            => 'midfielder',
                'date_of_birth'       => '2001-02-22',
                'place_of_birth'      => 'Rionegro, Antioquia',
                'height_cm'           => 178,
                'weight_kg'           => 72,
                'international_caps'  => 15,
                'international_goals' => 2,
                'strong_foot'         => 'right',
                'club'                => 'Real Betis',
            ],
            [
                'first_name'          => 'Kevin',
                'last_name'           => 'Castaño',
                'position'            => 'midfielder',
                'date_of_birth'       => '1998-02-23',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 176,
                'weight_kg'           => 71,
                'international_caps'  => 10,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'River Plate',
            ],
            [
                'first_name'          => 'Gustavo',
                'last_name'           => 'Puerta',
                'position'            => 'midfielder',
                'date_of_birth'       => '2003-08-29',
                'place_of_birth'      => 'Manizales, Caldas',
                'height_cm'           => 178,
                'weight_kg'           => 73,
                'international_caps'  => 8,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Racing de Santander',
            ],
            [
                'first_name'          => 'Juan Manuel',
                'last_name'           => 'Rengifo',
                'position'            => 'midfielder',
                'date_of_birth'       => '2004-01-05',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 175,
                'weight_kg'           => 68,
                'international_caps'  => 3,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Atlético Nacional',
            ],
            [
                'first_name'          => 'Johan',
                'last_name'           => 'Rojas',
                'position'            => 'midfielder',
                'date_of_birth'       => '2000-10-25',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 172,
                'weight_kg'           => 68,
                'international_caps'  => 8,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Vasco da Gama',
            ],
            [
                'first_name'          => 'Juanfer',
                'last_name'           => 'Quintero',
                'position'            => 'midfielder',
                'date_of_birth'       => '1993-01-18',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 166,
                'weight_kg'           => 64,
                'international_caps'  => 35,
                'international_goals' => 6,
                'strong_foot'         => 'left',
                'club'                => 'River Plate',
            ],
            [
                'first_name'          => 'Juan Camilo',
                'last_name'           => 'Portilla',
                'position'            => 'midfielder',
                'date_of_birth'       => '2001-12-05',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 173,
                'weight_kg'           => 70,
                'international_caps'  => 8,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Athletico Paranaense',
            ],
            [
                'first_name'          => 'Jordan',
                'last_name'           => 'Barrera',
                'position'            => 'midfielder',
                'date_of_birth'       => '1999-05-24',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 178,
                'weight_kg'           => 73,
                'international_caps'  => 5,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Botafogo',
            ],
            [
                'first_name'          => 'Jhon',
                'last_name'           => 'Solís',
                'position'            => 'midfielder',
                'date_of_birth'       => '2001-03-26',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 175,
                'weight_kg'           => 70,
                'international_caps'  => 5,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Birmingham City',
            ],
            [
                'first_name'          => 'Jefferson',
                'last_name'           => 'Lerma',
                'position'            => 'midfielder',
                'date_of_birth'       => '1994-10-25',
                'place_of_birth'      => 'Palmira, Valle del Cauca',
                'height_cm'           => 180,
                'weight_kg'           => 76,
                'international_caps'  => 78,
                'international_goals' => 4,
                'strong_foot'         => 'right',
                'club'                => 'Crystal Palace',
            ],
            [
                'first_name'          => 'Richard',
                'last_name'           => 'Ríos',
                'position'            => 'midfielder',
                'date_of_birth'       => '2001-02-07',
                'place_of_birth'      => 'Apartadó, Antioquia',
                'height_cm'           => 176,
                'weight_kg'           => 72,
                'international_caps'  => 28,
                'international_goals' => 2,
                'strong_foot'         => 'right',
                'club'                => 'Benfica',
            ],
            [
                'first_name'          => 'Jhon',
                'last_name'           => 'Arias',
                'position'            => 'midfielder',
                'date_of_birth'       => '1997-09-02',
                'place_of_birth'      => 'Armenia, Quindío',
                'height_cm'           => 177,
                'weight_kg'           => 72,
                'international_caps'  => 30,
                'international_goals' => 4,
                'strong_foot'         => 'right',
                'club'                => 'Palmeiras',
            ],
            [
                'first_name'          => 'Wilmar',
                'last_name'           => 'Barrios',
                'position'            => 'midfielder',
                'date_of_birth'       => '1993-10-16',
                'place_of_birth'      => 'Barranquilla, Atlántico',
                'height_cm'           => 175,
                'weight_kg'           => 71,
                'international_caps'  => 72,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Zenit',
            ],
            [
                'first_name'          => 'Juan',
                'last_name'           => 'Cuadrado',
                'position'            => 'midfielder',
                'date_of_birth'       => '1988-05-26',
                'place_of_birth'      => 'Necoclí, Antioquia',
                'height_cm'           => 176,
                'weight_kg'           => 70,
                'international_caps'  => 105,
                'international_goals' => 17,
                'strong_foot'         => 'right',
                'club'                => 'Pisa Calcio',
            ],
            [
                'first_name'          => 'Yaser',
                'last_name'           => 'Asprilla',
                'position'            => 'midfielder',
                'date_of_birth'       => '2003-02-14',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 177,
                'weight_kg'           => 70,
                'international_caps'  => 18,
                'international_goals' => 2,
                'strong_foot'         => 'right',
                'club'                => 'Galatasaray',
            ],

            // ── DELANTEROS ───────────────────────────────────────────────────
            [
                'first_name'          => 'Luis',
                'last_name'           => 'Díaz',
                'position'            => 'forward',
                'date_of_birth'       => '1997-01-13',
                'place_of_birth'      => 'Barrancas, La Guajira',
                'height_cm'           => 178,
                'weight_kg'           => 68,
                'international_caps'  => 68,
                'international_goals' => 22,
                'strong_foot'         => 'left',
                'club'                => 'Bayern Munich',
            ],
            [
                'first_name'          => 'Jhon',
                'last_name'           => 'Córdoba',
                'position'            => 'forward',
                'date_of_birth'       => '1993-04-11',
                'place_of_birth'      => 'El Carmen de Bolívar, Bolívar',
                'height_cm'           => 191,
                'weight_kg'           => 90,
                'international_caps'  => 35,
                'international_goals' => 9,
                'strong_foot'         => 'right',
                'club'                => 'Krasnodar',
            ],
            [
                'first_name'          => 'Luis',
                'last_name'           => 'Suárez',
                'position'            => 'forward',
                'date_of_birth'       => '1997-12-03',
                'place_of_birth'      => 'Armenia, Quindío',
                'height_cm'           => 180,
                'weight_kg'           => 75,
                'international_caps'  => 25,
                'international_goals' => 6,
                'strong_foot'         => 'right',
                'club'                => 'Sporting CP',
            ],
            [
                'first_name'          => 'Sebastián',
                'last_name'           => 'Villa',
                'position'            => 'forward',
                'date_of_birth'       => '1997-03-11',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 171,
                'weight_kg'           => 67,
                'international_caps'  => 15,
                'international_goals' => 3,
                'strong_foot'         => 'left',
                'club'                => 'Independiente Rivadavia',
            ],
            [
                'first_name'          => 'Neyser',
                'last_name'           => 'Villarreal',
                'position'            => 'forward',
                'date_of_birth'       => '1999-04-08',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 175,
                'weight_kg'           => 70,
                'international_caps'  => 5,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Cruzeiro',
            ],
            [
                'first_name'          => 'Kevin',
                'last_name'           => 'Viveros',
                'position'            => 'forward',
                'date_of_birth'       => '2001-04-15',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 173,
                'weight_kg'           => 68,
                'international_caps'  => 4,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Athletico Paranaense',
            ],
            [
                'first_name'          => 'John Steven',
                'last_name'           => 'Mendoza',
                'position'            => 'forward',
                'date_of_birth'       => '2000-08-05',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 178,
                'weight_kg'           => 73,
                'international_caps'  => 6,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Athletico Paranaense',
            ],
            [
                'first_name'          => 'Edwuin',
                'last_name'           => 'Cetré',
                'position'            => 'forward',
                'date_of_birth'       => '1996-03-24',
                'place_of_birth'      => 'Quibdó, Chocó',
                'height_cm'           => 170,
                'weight_kg'           => 67,
                'international_caps'  => 15,
                'international_goals' => 2,
                'strong_foot'         => 'right',
                'club'                => 'Estudiantes de La Plata',
            ],
            [
                'first_name'          => 'Jhon',
                'last_name'           => 'Durán',
                'position'            => 'forward',
                'date_of_birth'       => '2003-12-13',
                'place_of_birth'      => 'Medellín, Antioquia',
                'height_cm'           => 188,
                'weight_kg'           => 82,
                'international_caps'  => 15,
                'international_goals' => 3,
                'strong_foot'         => 'right',
                'club'                => 'Zenit',
            ],
            [
                'first_name'          => 'Andrés',
                'last_name'           => 'Gómez',
                'position'            => 'forward',
                'date_of_birth'       => '2003-09-09',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 180,
                'weight_kg'           => 74,
                'international_caps'  => 5,
                'international_goals' => 1,
                'strong_foot'         => 'right',
                'club'                => 'Vasco da Gama',
            ],
            [
                'first_name'          => 'Rafael',
                'last_name'           => 'Santos Borré',
                'position'            => 'forward',
                'date_of_birth'       => '1995-09-15',
                'place_of_birth'      => 'Barranquilla, Atlántico',
                'height_cm'           => 178,
                'weight_kg'           => 73,
                'international_caps'  => 42,
                'international_goals' => 13,
                'strong_foot'         => 'right',
                'club'                => 'Internacional',
            ],
            [
                'first_name'          => 'Jaminton',
                'last_name'           => 'Campaz',
                'position'            => 'forward',
                'date_of_birth'       => '2000-09-02',
                'place_of_birth'      => 'Santiago de Cali, Valle del Cauca',
                'height_cm'           => 174,
                'weight_kg'           => 68,
                'international_caps'  => 8,
                'international_goals' => 2,
                'strong_foot'         => 'right',
                'club'                => 'Rosario Central',
            ],
            [
                'first_name'          => 'Johan',
                'last_name'           => 'Carbonero',
                'position'            => 'forward',
                'date_of_birth'       => '1996-06-28',
                'place_of_birth'      => 'Colombia',
                'height_cm'           => 172,
                'weight_kg'           => 68,
                'international_caps'  => 6,
                'international_goals' => 0,
                'strong_foot'         => 'right',
                'club'                => 'Internacional',
            ],
            [
                'first_name'          => 'Cucho',
                'last_name'           => 'Hernández',
                'position'            => 'forward',
                'date_of_birth'       => '1999-04-22',
                'place_of_birth'      => 'La Ceja, Antioquia',
                'height_cm'           => 178,
                'weight_kg'           => 75,
                'international_caps'  => 30,
                'international_goals' => 7,
                'strong_foot'         => 'right',
                'club'                => 'Real Betis',
            ],
        ];

        foreach ($players as $data) {
            $club = Club::where('name', $data['club'])->first();
            $fullName = trim($data['first_name'] . ' ' . $data['last_name']);
            $slug     = Str::slug($fullName);

            Player::updateOrCreate(
                ['slug' => $slug],
                [
                    'federation_id'       => $federationId,
                    'club_id'             => $club?->id,
                    'first_name'          => $data['first_name'],
                    'last_name'           => $data['last_name'],
                    'full_name'           => $fullName,
                    'slug'                => $slug,
                    'photo_url'           => "players/colombia/{$slug}.jpg",
                    'position'            => $data['position'],
                    'jersey_number'       => null,
                    'date_of_birth'       => $data['date_of_birth'],
                    'place_of_birth'      => $data['place_of_birth'],
                    'nationality'         => 'Colombia',
                    'height_cm'           => $data['height_cm'],
                    'weight_kg'           => $data['weight_kg'],
                    'international_caps'  => $data['international_caps'],
                    'international_goals' => $data['international_goals'],
                    'strong_foot'         => $data['strong_foot'],
                    'active'              => true,
                    'in_wc_prelista_2026' => true,
                ]
            );
        }
    }
}
