import { Formation, FormationName } from "@/types";

export const FORMATIONS: Record<FormationName, Formation> = {
  "4-3-3": {
    name: "4-3-3",
    positions: [
      { slot: "GK",  label: "Portero",    x: 50, y: 86 },
      { slot: "RB",  label: "Lat. Der.",  x: 82, y: 67 },
      { slot: "CB1", label: "Central",    x: 61, y: 69 },
      { slot: "CB2", label: "Central",    x: 39, y: 69 },
      { slot: "LB",  label: "Lat. Izq.",  x: 18, y: 67 },
      { slot: "CM1", label: "Medioc.",    x: 72, y: 48 },
      { slot: "CM2", label: "Medioc.",    x: 50, y: 46 },
      { slot: "CM3", label: "Medioc.",    x: 28, y: 48 },
      { slot: "RW",  label: "Ext. Der.",  x: 78, y: 22 },
      { slot: "ST",  label: "Delantero",  x: 50, y: 18 },
      { slot: "LW",  label: "Ext. Izq.",  x: 22, y: 22 },
    ],
  },
  "4-4-2": {
    name: "4-4-2",
    positions: [
      { slot: "GK",  label: "Portero",    x: 50, y: 86 },
      { slot: "RB",  label: "Lat. Der.",  x: 82, y: 68 },
      { slot: "CB1", label: "Central",    x: 61, y: 70 },
      { slot: "CB2", label: "Central",    x: 39, y: 70 },
      { slot: "LB",  label: "Lat. Izq.",  x: 18, y: 68 },
      { slot: "RM",  label: "M. Der.",    x: 78, y: 47 },
      { slot: "CM1", label: "Medioc.",    x: 58, y: 47 },
      { slot: "CM2", label: "Medioc.",    x: 38, y: 47 },
      { slot: "LM",  label: "M. Izq.",    x: 18, y: 47 },
      { slot: "ST1", label: "Delantero",  x: 62, y: 20 },
      { slot: "ST2", label: "Delantero",  x: 38, y: 20 },
    ],
  },
  "4-2-3-1": {
    name: "4-2-3-1",
    positions: [
      { slot: "GK",  label: "Portero",    x: 50, y: 86 },
      { slot: "RB",  label: "Lat. Der.",  x: 82, y: 70 },
      { slot: "CB1", label: "Central",    x: 61, y: 72 },
      { slot: "CB2", label: "Central",    x: 39, y: 72 },
      { slot: "LB",  label: "Lat. Izq.",  x: 18, y: 70 },
      { slot: "DM1", label: "Vol. Def.",  x: 62, y: 55 },
      { slot: "DM2", label: "Vol. Def.",  x: 38, y: 55 },
      { slot: "RM",  label: "M. Der.",    x: 78, y: 37 },
      { slot: "AM",  label: "Mediap.",    x: 50, y: 35 },
      { slot: "LM",  label: "M. Izq.",    x: 22, y: 37 },
      { slot: "ST",  label: "Delantero",  x: 50, y: 17 },
    ],
  },
  "3-5-2": {
    name: "3-5-2",
    positions: [
      { slot: "GK",  label: "Portero",    x: 50, y: 86 },
      { slot: "CB1", label: "Central",    x: 68, y: 70 },
      { slot: "CB2", label: "Central",    x: 50, y: 72 },
      { slot: "CB3", label: "Central",    x: 32, y: 70 },
      { slot: "RWB", label: "Car. Der.",  x: 88, y: 51 },
      { slot: "CM1", label: "Medioc.",    x: 68, y: 48 },
      { slot: "CM2", label: "Medioc.",    x: 50, y: 46 },
      { slot: "CM3", label: "Medioc.",    x: 32, y: 48 },
      { slot: "LWB", label: "Car. Izq.",  x: 12, y: 51 },
      { slot: "ST1", label: "Delantero",  x: 63, y: 20 },
      { slot: "ST2", label: "Delantero",  x: 37, y: 20 },
    ],
  },
  "4-1-4-1": {
    name: "4-1-4-1",
    positions: [
      { slot: "GK",  label: "Portero",    x: 50, y: 86 },
      { slot: "RB",  label: "Lat. Der.",  x: 82, y: 70 },
      { slot: "CB1", label: "Central",    x: 61, y: 72 },
      { slot: "CB2", label: "Central",    x: 39, y: 72 },
      { slot: "LB",  label: "Lat. Izq.",  x: 18, y: 70 },
      { slot: "DM",  label: "Vol. Def.",  x: 50, y: 57 },
      { slot: "RM",  label: "M. Der.",    x: 78, y: 42 },
      { slot: "CM1", label: "Medioc.",    x: 59, y: 40 },
      { slot: "CM2", label: "Medioc.",    x: 41, y: 40 },
      { slot: "LM",  label: "M. Izq.",    x: 22, y: 42 },
      { slot: "ST",  label: "Delantero",  x: 50, y: 17 },
    ],
  },
};
